# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 14:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_parent',
        ),
    ]
