# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 06:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_auto_20180213_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Choose a name for this period of grades, Semester, yearly or monthly test. However it suits your needs the best', max_length=225)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='grade',
            name='period_end',
        ),
        migrations.RemoveField(
            model_name='grade',
            name='period_start',
        ),
        migrations.AddField(
            model_name='grade',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='semester', to='academics.Semester'),
        ),
    ]
