# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-14 08:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_auto_20180214_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grade',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grades', to='academics.Semester'),
        ),
    ]
