# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-02-28 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_auto_20180214_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollcall',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rollcall', to=settings.AUTH_USER_MODEL),
        ),
    ]
